# Generated by Django 3.0 on 2020-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_post', models.DateField()),
                ('tipo_postagem', models.CharField(max_length=25)),
                ('tipo_envio', models.CharField(max_length=100)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('ctt_id', models.IntegerField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('entregas_d_mais', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo_baixa', models.CharField(max_length=100)),
                ('sla', models.CharField(max_length=100)),
                ('mot_devolucao_id', models.IntegerField(blank=True, null=True)),
                ('mot_devolucao', models.CharField(blank=True, max_length=150, null=True)),
                ('baixa_via_rt', models.CharField(max_length=5)),
                ('alvo', models.CharField(max_length=30)),
                ('tentativas', models.SmallIntegerField(blank=True, null=True)),
                ('qtde', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmp_site',
                'managed': False,
            },
        ),
    ]
